name = "plinko-jeuxenligne-fr"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=plinko-jeuxenligne.fr"
HMAC_KEY = "7bb3869b13319ad978c031753e23d3f0fb8e0a047080b72ba31f54c0f8ebd933"
COOKIE_NAME = "utf"
PLAY_PATH = "try-now"
BUTTON_ID = "p99b331718fdb311e81322f76a72b292d"
GATE_SALT = "2a2161f905cce585"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "9hin"
CTA_SELECTOR = ".play-button"
